name: TesseractLib
version: ${project.version}
main: onl.tesseract.tesseractlib.TesseractLib
api-version: 1.16
depend: [Multiverse-Core, Vault, LuckPerms]

commands:
  animation:
    aliases: animation
    usage: "/animation"
    description: Pour tester des animations
    permission: tesseract.staff
  equipment:
    aliases: eq
    usage: "/equipement"
    description: Pour tester le menu équipements
  msg:
    aliases: [ tell, w ]
    usage: "/msg {pseudo} {message}"
    description: Envoie un message privé
  reply:
    aliases: [ r ]
    usage: "/r {message}"
    description: Répondre à un message privé
#  socialspy:
#    usage: "/socialspy"
#    description: Espionner les conversations
#    permission: tesseract.staff.socialspy