name: TesseractLib
version: ${project.version}
main: onl.tesseract.tesseractlib.TesseractLib
api-version: 1.16
depend: [Multiverse-Core, Vault, LuckPerms, PlaceholderAPI]

commands:
  animation:
    aliases: animation
    usage: "/animation"
    description: Pour tester des animations
    permission: tesseract.staff
  equipment:
    aliases: [eq, equipement ]
    usage: "/equipement"
    description: Pour tester le menu équipements
    permission: tesseract.equipment
  msg:
    aliases: [ tell, w ]
    usage: "/msg {pseudo} {message}"
    description: Envoie un message privé
  reply:
    aliases: [ r ]
    usage: "/r {message}"
    description: Répondre à un message privé
  socialspy:
    usage: "/socialspy"
    description: Espionner les conversations
    permission: tesseract.staff.socialspy
  familier:
    aliases: [pet, pets]
    usage: "/familier"
    description: Permet d'ouvrir le menu des familiers
  cosmetic:
    usage: "/cosmetic"
    description: Permet de donner ou reprendre des cosmetiques
  elytraTrail:
    usage: "/elytraTrail"
    description: Permet d'ouvrir le menu de selection des trails d'elytra
  boutique:
    usage: "/boutique"
    description: Ouvre la boutique
  marketCurrency:
    usage: "/marketCurrency"
    description: Donne des lys d'or au joueur.
  votegoal:
    usage: "/votegoal help"
    description: Gérer les vote goal
    permission: tesseract.staff.votegoal
  vote:
    usage: "/vote"
    description: Voter pour le serveur